TABLE_(FILES)
	INT_	(F_ID) PRIMARY_KEY
	STRING_	(F_NAME, 100)
	STRING_	(F_FILENAME, 200)
	DATE_	(F_PARSED)
	STRING_	(F_CMTEXT, 512)
END_TABLE

TABLE_(NODE)
   INT_     (N_ID) PRIMARY_KEY
   INT_		(N_FID)
   STRING_  (N_NAME, 100)
   INT_		(N_ADDRESS)
   STRING_	(N_CMTEXT, 512)
END_TABLE

TABLE_(OMSG)
	INT_	(M_ID) PRIMARY_KEY
	INT_	(M_FID)
	STRING_ (M_NAME,80)
	INT_	(M_DLC)
	STRING_ (M_SENDER,80)
	DATE_	(M_MODIFIED)
	STRING_	(M_CMTEXT, 512)
END_TABLE

TABLE_(SIG)
	INT_	(S_ID) PRIMARY_KEY
	INT_	(S_FID)
	INT_	(S_SID)
	STRING_ (S_NAME,80)
	INT_	(S_BITSTART)
	INT_	(S_BITSIZE)
	INT_	(S_BYTEORDER)
	INT_	(S_SIGN)
	DOUBLE_	(S_SCALE)
	DOUBLE_	(S_OFFSET)
	INT_	(S_MIN)
	INT_	(S_MAX)
	STRING_	(S_UNITS, 80)
	STRING_	(S_DSTNODE, 200)
	DATE_	(S_MODIFIED)
	STRING_	(S_CMTEXT, 512)
END_TABLE

TABLE_(SIGDSTNODE)
	INT_	(D_ID) PRIMARY_KEY
	INT_	(D_FID)
	INT_	(D_SID)
	INT_	(D_NID)
END_TABLE

/*
TABLE_(LCM)
	INT_	(C_ID) PRIMARY_KEY
	INT_	(C_FID)
	INT_	(C_TYPE)
	INT_	(C_MID)
	INT_	(C_SID)
	STRING_	(C_NAME,80)
	STRING_	(C_TEXT, 512)
END_TABLE
*/

TABLE_(LNS)
	INT_	(NS_ID) PRIMARY_KEY
	INT_	(NS_FID)
	STRING_	(NS_NAME,80)
END_TABLE

TABLE_(LBU)
	INT_	(BU_ID) PRIMARY_KEY
	INT_	(BU_FID)
	STRING_	(BU_NAME,80)
	STRING_	(S_CMTEXT, 512)
END_TABLE

TABLE_(LBA)
	INT_	(BA_ID) PRIMARY_KEY
	INT_	(BA_FID)
	INT_	(BA_NSID1)
	STRING_	(BA_NAME,80)
	INT_	(BA_TYPE)
	STRING_	(BA_TYPENAME,80)
	INT_	(BA_MIN)
	INT_	(BA_MAX)
	STRING_	(BA_VALSTRING,80)
END_TABLE

TABLE_(LBAL)
	INT_	(BAL_ID) PRIMARY_KEY
	INT_	(BAL_FID)
	INT_	(BAL_NSID1)
	STRING_	(BAL_NAME,80)
	INT_	(BAL_NSID2)
	INT_	(BAL_NID)
	INT_	(BAL_TYPE)
	INT_	(BAL_MID)
	INT_	(BAL_SID)
	STRING_	(BAL_VALSTRING,80)
	INT_	(BAL_VALINT)
END_TABLE